version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
build_script:
- cmd: build.cmd
test: off
artifacts:
- path: '*.nupkg'
deploy: off
